### ISSUE TITLE
Hatari core. Joystick not working in retroarch on xbox. 

### ISSUE THREAD

**Issue by borrelnoten** [libretro/hatari#73]
Trying to use my xbox s controler. Hatari runs oke in retroarch. I can start games and move mouse but i can not use the joystick. Also i can not press fire using the controler.

In hatari menu the real joystick shows not defined.

**Comment by bbbradsmith** [comment]
Press select to toggle between joystick and mouse mode.

The hatari menu's joystick settings are not functional in this core. Joystick is always enabled.

**Comment by borrelnoten** [comment]
Yes i tried that to switch between mouse mode and joystick mode but it does not help.
zaterdag, 30 januari 2021, 01:39a.m. +01:00 van Brad Smith  notifications@github.com :

**Comment by borrelnoten** [comment]
joypad works for magic pockets. not sure why some games do not pick-up the x-box controler

**Comment by bbbradsmith** [comment]
I'm curious how old the build you are using is, because there was a recent fix to the input system because some methods games used to read the controller were not working ( see #50 ). If your build is just old, that fix ( #68 ) should address it. You haven't named any specific games that don't work for you yet. Altered Beast and Alien Syndrome are two that I know didn't work before the fix. Bubble Bobble and Toki are two that I know did work before the fix.

Can you be more specific about what doesn't work? What specific build are you using? It seems quite possible that this is already fixed with a newer build.

**Comment by borrelnoten** [comment]
I will need to install the latest windows build for this.core to test. Where can i download this core dll ?

**Comment by bbbradsmith** [comment]
I don't know anything about r-type's fork. _This_ core can be downloaded from RetroArch's built-in updater.

**Comment by borrelnoten** [comment]
Not when installed on x-box in dev mode unfortunatly. I have installed retroarch 3 weeks ago so i think it has the latest version? woensdag, 17 februari 2021, 00:27a.m. +01:00 van Brad Smith  notifications@github.com :

**Comment by bbbradsmith** [comment]
After loading a game, go to the RetroArch menu. In the bottom left corner it should say something like "1.9.0 - Hatari (46dc6d9)". That's the build identifier that can tell us what build of the core you have.

**Comment by borrelnoten** [comment]
fix it by manualy updating to version 1.8 of the hatari for libretro core. Downloaded the windows 64 version, updated the cores and manualy replaced the cores on the xbox cores directory of retroarch.
